apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xxek9qs0r-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xxek9qs0r-dotnet-basic-gitops